"""Constants for EASUN SMX integration."""
from homeassistant.const import CONF_HOST, CONF_PORT

DOMAIN = "easun_smx"
DEFAULT_PORT = 502
DEFAULT_SCAN_INTERVAL = 30

# Register addresses extracted from actual inverter responses
# Format: address is the Modbus register address from the protocol
REGISTERS = {
    # Configuration Parameters (Holding Registers - Read/Write)
    "output_priority": {
        "address": 0xE204,
        "type": "holding",
        "unit": "",
        "name": "Output Priority",
        "scale": 1.0,
        "device_class": None,
    },
    "output_frequency": {
        "address": 0xE209,
        "type": "holding",
        "unit": "Hz",
        "name": "Output Frequency",
        "scale": 0.01,
        "device_class": "frequency",
    },
    "ac_input_voltage_range": {
        "address": 0xE20B,
        "type": "holding",
        "unit": "",
        "name": "AC Input Voltage Range",
        "scale": 1.0,
        "device_class": None,
    },
    "charger_source_priority": {
        "address": 0xE20F,
        "type": "holding",
        "unit": "",
        "name": "Charger Source Priority",
        "scale": 1.0,
        "device_class": None,
    },
    "max_charger_current": {
        "address": 0xE20A,
        "type": "holding",
        "unit": "A",
        "name": "Max Charger Current",
        "scale": 0.1,
        "device_class": "current",
    },
    "max_ac_charger_current": {
        "address": 0xE205,
        "type": "holding",
        "unit": "A",
        "name": "Max AC Charger Current",
        "scale": 0.1,
        "device_class": "current",
    },
    "output_voltage_set": {
        "address": 0xE208,
        "type": "holding",
        "unit": "V",
        "name": "Output Voltage Set",
        "scale": 0.1,
        "device_class": "voltage",
    },
    
    # Battery Configuration
    "battery_type": {
        "address": 0xE004,
        "type": "holding",
        "unit": "",
        "name": "Battery Type",
        "scale": 1.0,
        "device_class": None,
    },
    "battery_boost_charge_voltage": {
        "address": 0xE008,
        "type": "holding",
        "unit": "V",
        "name": "Battery Boost Charge Voltage",
        "scale": 0.1,
        "device_class": "voltage",
    },
    "battery_floating_charge_voltage": {
        "address": 0xE009,
        "type": "holding",
        "unit": "V",
        "name": "Battery Floating Charge Voltage",
        "scale": 0.1,
        "device_class": "voltage",
    },
    "battery_over_discharge_voltage": {
        "address": 0xE00D,
        "type": "holding",
        "unit": "V",
        "name": "Battery Over Discharge Voltage",
        "scale": 0.1,
        "device_class": "voltage",
    },
    "battery_under_voltage_alarm": {
        "address": 0xE00C,
        "type": "holding",
        "unit": "V",
        "name": "Battery Under Voltage Alarm",
        "scale": 0.1,
        "device_class": "voltage",
    },
    "battery_discharge_limit_voltage": {
        "address": 0xE00E,
        "type": "holding",
        "unit": "V",
        "name": "Battery Discharge Limit Voltage",
        "scale": 0.1,
        "device_class": "voltage",
    },
    "battery_undervoltage_recovery": {
        "address": 0xE00B,
        "type": "holding",
        "unit": "V",
        "name": "Battery Undervoltage Recovery",
        "scale": 0.1,
        "device_class": "voltage",
    },
    "battery_charge_recovery": {
        "address": 0xE00A,
        "type": "holding",
        "unit": "V",
        "name": "Battery Charge Recovery",
        "scale": 0.1,
        "device_class": "voltage",
    },
    "max_pv_charger_current": {
        "address": 0xE001,
        "type": "holding",
        "unit": "A",
        "name": "Max PV Charger Current",
        "scale": 0.1,
        "device_class": "current",
    },
    
    # Real-time Monitoring (Input Registers - Read Only)
    "pv_voltage": {
        "address": 0x0107,
        "type": "input",
        "unit": "V",
        "name": "PV Voltage",
        "scale": 0.1,
        "device_class": "voltage",
    },
    "pv_current": {
        "address": 0x0108,
        "type": "input",
        "unit": "A",
        "name": "PV Current",
        "scale": 0.1,
        "device_class": "current",
    },
    "pv_power": {
        "address": 0x0109,
        "type": "input",
        "unit": "W",
        "name": "PV Power",
        "scale": 1.0,
        "device_class": "power",
    },
    "line_voltage": {
        "address": 0x0213,
        "type": "input",
        "unit": "V",
        "name": "Line Voltage",
        "scale": 0.1,
        "device_class": "voltage",
    },
    "line_current": {
        "address": 0x0214,
        "type": "input",
        "unit": "A",
        "name": "Line Current",
        "scale": 0.1,
        "device_class": "current",
    },
    "line_frequency": {
        "address": 0x0215,
        "type": "input",
        "unit": "Hz",
        "name": "Line Frequency",
        "scale": 0.01,
        "device_class": "frequency",
    },
    "battery_voltage": {
        "address": 0x0101,
        "type": "input",
        "unit": "V",
        "name": "Battery Voltage",
        "scale": 0.1,
        "device_class": "voltage",
    },
    "battery_current": {
        "address": 0x0102,
        "type": "input",
        "unit": "A",
        "name": "Battery Current",
        "scale": 0.1,
        "device_class": "current",
        "signed": True,
    },
    "battery_soc": {
        "address": 0x0100,
        "type": "input",
        "unit": "%",
        "name": "Battery SOC",
        "scale": 1.0,
        "device_class": "battery",
    },
    "charge_current_by_line": {
        "address": 0x021E,
        "type": "input",
        "unit": "A",
        "name": "Charge Current By Line",
        "scale": 0.1,
        "device_class": "current",
        "signed": True,
    },
    "load_voltage": {
        "address": 0x0216,
        "type": "input",
        "unit": "V",
        "name": "Load Voltage",
        "scale": 0.1,
        "device_class": "voltage",
    },
    "load_current": {
        "address": 0x0219,
        "type": "input",
        "unit": "A",
        "name": "Load Current",
        "scale": 0.1,
        "device_class": "current",
    },
    "load_active_power": {
        "address": 0x021B,
        "type": "input",
        "unit": "W",
        "name": "Load Active Power",
        "scale": 1.0,
        "device_class": "power",
    },
    "load_apparent_power": {
        "address": 0x021C,
        "type": "input",
        "unit": "VA",
        "name": "Load Apparent Power",
        "scale": 1.0,
        "device_class": "apparent_power",
    },
    "load_ratio": {
        "address": 0x021F,
        "type": "input",
        "unit": "%",
        "name": "Load Ratio",
        "scale": 1.0,
        "device_class": None,
    },
    "temperature_dc": {
        "address": 0x0220,
        "type": "input",
        "unit": "°C",
        "name": "Temperature DC",
        "scale": 0.1,
        "device_class": "temperature",
        "signed": True,
    },
    "temperature_ac": {
        "address": 0x0221,
        "type": "input",
        "unit": "°C",
        "name": "Temperature AC",
        "scale": 0.1,
        "device_class": "temperature",
        "signed": True,
    },
    "temperature_tr": {
        "address": 0x0222,
        "type": "input",
        "unit": "°C",
        "name": "Temperature TR",
        "scale": 0.1,
        "device_class": "temperature",
        "signed": True,
    },
    "inverter_current": {
        "address": 0x0217,
        "type": "input",
        "unit": "A",
        "name": "Inverter Current",
        "scale": 0.1,
        "device_class": "current",
    },
    "inverter_frequency": {
        "address": 0x0218,
        "type": "input",
        "unit": "Hz",
        "name": "Inverter Frequency",
        "scale": 0.01,
        "device_class": "frequency",
    },
    "battery_charge_step": {
        "address": 0x010B,
        "type": "input",
        "unit": "",
        "name": "Battery Charge Step",
        "scale": 1.0,
        "device_class": None,
    },
    "bus_voltage": {
        "address": 0x0212,
        "type": "input",
        "unit": "V",
        "name": "Bus Voltage",
        "scale": 0.1,
        "device_class": "voltage",
    },
    "machine_state": {
        "address": 0x0210,
        "type": "input",
        "unit": "",
        "name": "Machine State",
        "scale": 1.0,
        "device_class": None,
    },
    
    # Energy Statistics
    "load_power_consumption_today": {
        "address": 0xF030,
        "type": "input",
        "unit": "kWh",
        "name": "Load Power Consumption Today",
        "scale": 0.1,
        "device_class": "energy",
    },
    "load_power_consumption_today_from_mains": {
        "address": 0xF03D,
        "type": "input",
        "unit": "kWh",
        "name": "Load Power Consumption Today From Mains",
        "scale": 0.1,
        "device_class": "energy",
    },
    "pv_cumulative_power_generation": {
        "address": 0xF038,
        "type": "input",
        "unit": "kWh",
        "name": "PV Cumulative Power Generation",
        "scale": 0.1,
        "device_class": "energy",
    },
    "cumulative_charge": {
        "address": 0xF046,
        "type": "input",
        "unit": "Ah",
        "name": "Cumulative Charge",
        "scale": 0.1,
        "device_class": None,
    },
    "accumulated_battery_charge_hours": {
        "address": 0xF034,
        "type": "input",
        "unit": "Ah",
        "name": "Accumulated Battery Charge Hours",
        "scale": 1.0,
        "device_class": None,
    },
    "accumulated_battery_discharge_time": {
        "address": 0xF036,
        "type": "input",
        "unit": "Ah",
        "name": "Accumulated Battery Discharge Time",
        "scale": 1.0,
        "device_class": None,
    },
    "load_cumulative_power_consumption": {
        "address": 0xF03A,
        "type": "input",
        "unit": "kWh",
        "name": "Load Cumulative Power Consumption",
        "scale": 0.1,
        "device_class": "energy",
    },
    "accumulated_load_from_mains_consumption": {
        "address": 0xF048,
        "type": "input",
        "unit": "kWh",
        "name": "Accumulated Load From Mains Consumption",
        "scale": 0.1,
        "device_class": "energy",
    },
    "pv_power_generation_today": {
        "address": 0xF02F,
        "type": "input",
        "unit": "kWh",
        "name": "PV Power Generation Today",
        "scale": 0.1,
        "device_class": "energy",
    },
    "battery_charge_today": {
        "address": 0xF02D,
        "type": "input",
        "unit": "Ah",
        "name": "Battery Charge Today",
        "scale": 1.0,
        "device_class": None,
    },
    "battery_discharge_today": {
        "address": 0xF02E,
        "type": "input",
        "unit": "Ah",
        "name": "Battery Discharge Today",
        "scale": 1.0,
        "device_class": None,
    },
}

# Value mappings
OUTPUT_PRIORITY_MAP = {
    0: "SOL",  # Solar First
    1: "UTI",  # Utility First
    2: "SBU",  # Solar-Battery-Utility
}

CHARGER_SOURCE_PRIORITY_MAP = {
    0: "CSO",  # PV first, then utility
    1: "SUB",  # PV and utility
    2: "SNU",  # Only PV
    3: "OSO",  # Only utility
}

AC_INPUT_VOLTAGE_RANGE_MAP = {
    0: "APPLIANCE",
    1: "UPS",
}

MACHINE_STATE_MAP = {
    0: "Power On",
    1: "Standby",
    2: "Initialization",
    3: "Soft Start",
    4: "Running in line",
    5: "Running in inverter",
    6: "Invert to line",
    7: "Line to invert",
    8: "Remain in line",
    9: "Remain in inverter",
    10: "Shutdown",
}

BATTERY_TYPE_MAP = {
    0: "AGM",
    1: "Flooded",
    2: "User",
    3: "TBD",
    4: "Pylontech",
    5: "WECO",
    6: "Soltaro",
    7: "BYD",
    8: "Pylon",
}